# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.network "private_network", ip: "192.168.121.23"
  config.vm.hostname = "kaiser"
  config.vm.provider "libvirt" do |domain|
    domain.cpus = 2
    domain.memory = 2048
  end
  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install mc dnsutils vim -y
  SHELL
end
