# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.network "private_network", ip: "192.168.121.22"
  config.vm.hostname = "tzar"
  config.vm.provider "libvirt" do |domain|
    domain.cpus = 2
    domain.memory = 2048
  end
end
