# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.network "private_network", ip: "192.168.121.22"
  config.vm.hostname = "tzar"
  config.vm.provider "libvirt" do |domain|
    domain.cpus = 2
    domain.memory = 2048
  end
  config.vm.synced_folder "./build", "/build",
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false,
    linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install mc dnsutils g++ gcc -y
  SHELL
end
