# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.network "private_network", ip: "192.168.121.22"
  config.vm.hostname = "tzar"
  config.vm.provider "libvirt" do |domain|
    domain.cpus = 2
    domain.memory = 2048
  end
  config.vm.provision "shell", 
    run: "always",
    inline: "echo \"nameserver $(ip r s | grep default | cut -f 3 -d' ')\" | tee /etc/resolv.conf"
  config.vm.synced_folder "./build", "/home/vagrant/build",
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false,
    linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
  config.vm.synced_folder "./source", "/home/vagrant/source",
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false,
    linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
  config.vm.synced_folder "./toolchains", "/home/vagrant/toolchains",
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false,
    linux__nfs_options: ['ro','no_subtree_check','all_squash','async']
  config.vm.provision "shell", inline: <<-SHELL
    dpkg --add-architecture i386
    apt-get update
    apt-get install build-essential cmake git -y
    apt-get install \
        qtbase5-dev qttools5-dev qttools5-dev-tools \
        libfontconfig1-dev libfreetype6-dev libjpeg-dev libpodofo-dev \
        libcurl4-openssl-dev libmad0-dev libasound2-dev libxcb1-dev libudev-dev libsnmp-dev -y
    apt-get install \
        g++-multilib gcc-multilib \
        libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386 -y
  SHELL
end
