# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.network "private_network", ip: "192.168.121.21"
  config.vm.hostname = "pharaoh"
  config.vm.provider "libvirt" do |domain|
    domain.cpus = 3
    domain.memory = 4096
  end
  config.vm.provision "shell", 
    run: "always",
    inline: "echo \"nameserver $(ip r s | grep default | cut -f 3 -d' ')\" | tee /etc/resolv.conf"
  config.vm.synced_folder "./build", "/home/vagrant/build",
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false,
    linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
  config.vm.synced_folder "./qt-5.2.1/toolchain/colibri-t20/", "/usr/local/colibri-t20",
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false,
    linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
  config.vm.synced_folder "./qt-5.2.1/toolchain/gcc-linaro-arm-linux-gnueabihf/", "/usr/local/gcc-linaro-arm-linux-gnueabihf/",
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false,
    linux__nfs_options: ['ro','no_subtree_check','all_squash','async']
  config.vm.provision "file", source: "./qt-5.2.1/build.sh", destination: "qt-5.2.1/build.sh"
  config.vm.provision "file", source: "./qt-5.2.1/linux-tegra2-qmake-conf.patch", destination: "qt-5.2.1/linux-tegra2-qmake-conf.patch"
  config.vm.provision "file", source: "./qt-5.2.1/sysroot-gles-fix.patch", destination: "qt-5.2.1/sysroot-gles-fix.patch"
  config.vm.provision "shell", inline: <<-SHELL
      dpkg --add-architecture i386
      apt-get update
      apt-get install mc dnsutils g++ g++-multilib gcc gcc-multilib -y
      apt-get install libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386 -y
  SHELL
end
