# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "private_network", ip: "192.168.121.24"
  config.vm.hostname = "sultan"
  config.vm.provider "libvirt" do |domain|
    domain.cpus = 4
    domain.memory = 6000
  end
  config.vm.provision "shell", env: { "HOST_HOME" => ENV['HOME'] }, inline: <<-SHELL
    echo "export QT_BUILD_PREFIX=$HOST_HOME/workspace/qt5/" >> /home/vagrant/.profile
  SHELL
  config.vm.provision "shell",
    run: "always",
    inline: "echo \"nameserver $(ip r s | grep default | cut -f 3 -d' ')\" | tee /etc/resolv.conf"
  config.vm.synced_folder "./build", "/home/vagrant/build",
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false,
    nfs_export: true,
    linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
  config.vm.provision "file", source: "./qt-5.2.1/build.sh", destination: "qt-5.2.1/build.sh"
  config.vm.provision "file", source: "./qt-5.5.1/build.sh", destination: "qt-5.5.1/build.sh"
  config.vm.provision "file", source: "./qt-5.11.3/build.sh", destination: "qt-5.11.3/build.sh"
  config.vm.provision "shell", inline: <<-SHELL
      sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
      apt-get update
      apt-get install mc dnsutils g++ gcc build-essential fakeroot devscripts -y
      apt-get install \
          libcurl4-openssl-dev libasound2-dev libudev-dev \
          libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev \
          libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev  \
          libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev libxcb-xfixes0-dev libxcb-shape0-dev \
          libxcb-randr0-dev libxcb-render-util0-dev libxcb-xinerama0-dev libxkbcommon-dev libxkbcommon-x11-dev \
          libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev -y
      apt-get build-dep qtbase5-dev -y
  SHELL
end
